### PR TITLE
Split boss update code into 3 separate files, so they can go into independent banks

### PR DESCRIPTION
**Pull request by michel-iwaniec**
* move bat code to src/boss_bat.c
* move minotaur code to src/boss_minotaur.c
* move reaper code to src/boss_reaper.c
* Make sure update_boss performs switch to correct bank / restore
* Make new_boss and update_boss functions NONBANKED
* Update built binaries

### CODE REVIEW

**Comment by untoxa** [comment]
a-m, why not use BANKED attribute on those functions? you switch and restore bank anyway

**Comment by michel-iwaniec** [comment]
> a-m, why not use BANKED attribute on those functions? you switch and restore bank anyway

Hmm, I think that will cause a banked far call using the sdcc_bcall functionality?

And while functional, it is quite slow in the current NES implementation. (in the future, I'd like to generate dedicated trampoline functions with a compiler / processing tool to handle this instead)

**Comment by untoxa** [comment]
i am sure it will not produce performance issues here :)

**Comment by untoxa** [comment]
i am suggesting to make those functions BANKED again.
ps: and probably one more post-processing tool is not a very good idea either. maybe better suggest that approach to SDCC devs for the native support?

**Comment by michel-iwaniec** [comment]
> i am sure it will not produce performance issues here :)

Yeah, you're right. The BANKED for bosses is probably negligible given that there's only one... and the map updates / enemy spawning (inactive in the boss levels) are currently the major source of lag AFAICT.

I've done the change to switch back to BANKED bosses on top of my other changes for tokumaru compression and lag reduction, as I'm a bit too far ahead to go back to this PR now.

**Pull request merged**
